serenity.project.name=Test Automation LocalHost
# properties
serenity.take.screenshots = FOR_EACH_ACTION
webdriver.driver = firefox
serenity.outputDirectory = target/site/serenity
# opcional: ajustar tiempo y nivel de logs
serenity.timeout = 10000